version: '3.7'

services:
  bot:
    build:
      context: .
    volumes:
      - ./bot:/bot
    command: [
      "sh",
      "-c",
      "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --reload --host 0.0.0.0 --port 2727",
    ]
    ports:
      - "2727:2727"
      - "5678:5678"
    env_file:
      - ./.env
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "./config/redis.conf:/redis.conf"
    command: ["redis-server", "/redis.conf"]
