version: '3.7'

services:
  bot:
    build:
      context: .
    volumes:
      - ./bot:/bot
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 2727 --reload"
    ports:
      - "2727:2727"
    env_file:
      - ./.env
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"


  redis:
    image: "redislabs/redismod"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    entrypoint: >
      redis-server
        --loadmodule /usr/lib/redis/modules/rejson.so
        --appendonly yes
